
name: Build and deploy on push

on: 
  push:
    branches: 
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      uses: LucaFeger/action-maven-cli@765e218a50f02a12a7596dc9e7321fc385888a27
      with:
        args: clean install
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    