
name: Build and deploy on push

on: 
  push:
    branches: 
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    